package ontologyRepresentations.greenContextOntology;


/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Datacenter.owl#Core
 *
 * @version generated on Sun Mar 07 13:11:11 EET 2010
 */
public interface Core extends Component {
}
