package ontologyRepresentations.greenContextOntology;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

import java.util.Collection;
import java.util.Iterator;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Datacenter.owl#CPU
 *
 * @version generated on Sun Mar 07 13:11:11 EET 2010
 */
public interface CPU extends Component {

    // Property http://www.owl-ontologies.com/Datacenter.owl#associatedCore
    Collection getAssociatedCore();

    RDFProperty getAssociatedCoreProperty();

    boolean hasAssociatedCore();

    Iterator listAssociatedCore();

    void addAssociatedCore(Core newAssociatedCore);

    void removeAssociatedCore(Core oldAssociatedCore);

    void setAssociatedCore(Collection newAssociatedCore);

    
    // Property http://www.owl-ontologies.com/Datacenter.owl#numberOfCores
    int getNumberOfCores();

    RDFProperty getNumberOfCoresProperty();

    boolean hasNumberOfCores();

    void setNumberOfCores(int newNumberOfCores);

}
