label=Create multiple individuals
description=Allows the user to enter several individuals at once
intro=html/individuals.html

page.0.label=instantiating class
page.0.prompt=select a class to instantiate

page.1.label=enter names
page.1.prompt=Enter individuals below

page.2.label=different
page.2.prompt=Make all individuals distinct? (All Different - including existing individuals of this class)
