package greenContextOntology;

import com.hp.hpl.jena.ontology.OntModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Datacenter.owl#Component
 *
 * @version generated on Sun Mar 07 13:11:11 EET 2010
 */
public interface Component extends Resource {

    // Property http://www.owl-ontologies.com/Datacenter.owl#maxAcceptableValue

    int getMaxAcceptableValue();

    RDFProperty getMaxAcceptableValueProperty();

    boolean hasMaxAcceptableValue();

    void setMaxAcceptableValue(int newMaxAcceptableValue);


    // Property http://www.owl-ontologies.com/Datacenter.owl#minAcceptableValue

    int getMinAcceptableValue();

    RDFProperty getMinAcceptableValueProperty();

    boolean hasMinAcceptableValue();

    void setMinAcceptableValue(int newMinAcceptableValue);


    // Property http://www.owl-ontologies.com/Datacenter.owl#total

    int getTotal();

    RDFProperty getTotalProperty();

    boolean hasTotal();

    void setTotal(int newTotal);


    // Property http://www.owl-ontologies.com/Datacenter.owl#used

    int getUsed();

    RDFProperty getUsedProperty();

    boolean hasUsed();

    void setUsed(int newUsed, OntModel model);
    // Property http://www.owl-ontologies.com/Datacenter.owl#weight

    float getWeight();

    RDFProperty getWeightProperty();

    boolean hasWeight();

    void setWeight(float newWeight);


    void restoreDefaultOptimumValues();
}
