package greenContextOntology;

import com.hp.hpl.jena.ontology.OntModel;
import edu.stanford.smi.protegex.owl.model.OWLIndividual;
import edu.stanford.smi.protegex.owl.swrl.exceptions.SWRLFactoryException;
import edu.stanford.smi.protegex.owl.swrl.model.SWRLFactory;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Datacenter.owl#ContextElement
 *
 * @version generated on Sun Mar 07 13:11:11 EET 2010
 */
 public interface ContextElement extends OWLIndividual {
     public void deleteInstance(OntModel ontModel, SWRLFactory swrlFactory) throws SWRLFactoryException;
 }
