package greenContextOntology;

import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Datacenter.owl#CPU
 *
 * @version generated on Sat Mar 06 16:14:39 EET 2010
 */
public interface CPU extends Component {

    // Property http://www.owl-ontologies.com/Datacenter.owl#associatedCore

    Collection getAssociatedCore();

    RDFProperty getAssociatedCoreProperty();

    boolean hasAssociatedCore();

    Iterator listAssociatedCore();

    void addAssociatedCore(Core newAssociatedCore);

    void removeAssociatedCore(Core oldAssociatedCore);

    void setAssociatedCore(Collection newAssociatedCore);


    // Property http://www.owl-ontologies.com/Datacenter.owl#total

    int getTotal();

    RDFProperty getTotalProperty();

    boolean hasTotal();

    void setTotal(int newTotal);


    // Property http://www.owl-ontologies.com/Datacenter.owl#used

    int getUsed();

    RDFProperty getUsedProperty();

    boolean hasUsed();

    void setUsed(int newUsed);
}
