package greenContextOntology;

import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Datacenter.owl#Policy
 *
 * @version generated on Sat Mar 06 16:14:39 EET 2010
 */
public interface Policy extends ContextElement {

    // Property http://www.owl-ontologies.com/Datacenter.owl#references

    Collection getReferences();

    RDFProperty getReferencesProperty();

    boolean hasReferences();

    Iterator listReferences();

    void addReferences(Object newReferences);

    void removeReferences(Object oldReferences);

    void setReferences(Collection newReferences);


    // Property http://www.owl-ontologies.com/Datacenter.owl#respected

    boolean getRespected();

    RDFProperty getRespectedProperty();

    boolean hasRespected();

    void setRespected(boolean newRespected);
}
