package greenContextOntology;

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Datacenter.owl#Received
 *
 * @version generated on Sun Mar 07 13:11:11 EET 2010
 */
public interface Received extends TaskInfo {
}
