package greenContextOntology;

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://swrl.stanford.edu/ontologies/3.3/swrla.owl#RuleGroup
 *
 * @version generated on Sun Mar 07 13:11:11 EET 2010
 */
public interface RuleGroup extends Entity {

    // Property http://swrl.stanford.edu/ontologies/3.3/swrla.owl#isRuleGroupEnabled

    boolean getIsRuleGroupEnabled();

    RDFProperty getIsRuleGroupEnabledProperty();

    boolean hasIsRuleGroupEnabled();

    void setIsRuleGroupEnabled(boolean newIsRuleGroupEnabled);
}
