package greenContextOntology;

import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

import com.hp.hpl.jena.ontology.OntModel;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Datacenter.owl#Server
 *
 * @version generated on Sun Mar 07 13:11:11 EET 2010
 */
public interface Server extends Resource {

    // Property http://www.owl-ontologies.com/Datacenter.owl#associatedCPU
    CPU getAssociatedCPU();

    RDFProperty getAssociatedCPUProperty();

    boolean hasAssociatedCPU();

    void setAssociatedCPU(CPU newAssociatedCPU);

    // Property http://www.owl-ontologies.com/Datacenter.owl#associatedMemory
    Memory getAssociatedMemory();

    RDFProperty getAssociatedMemoryProperty();

    boolean hasAssociatedMemory();

    void setAssociatedMemory(Memory newAssociatedMemory);

    // Property http://www.owl-ontologies.com/Datacenter.owl#associatedStorage
    Storage getAssociatedStorage();

    RDFProperty getAssociatedStorageProperty();

    boolean hasAssociatedStorage();

    void setAssociatedStorage(Storage newAssociatedStorage);


    // Property http://www.owl-ontologies.com/Datacenter.owl#isInLowPowerState

    boolean getIsInLowPowerState();

    RDFProperty getIsInLowPowerStateProperty();

    boolean hasIsInLowPowerState();

    void setIsInLowPowerState(boolean newIsInLowPowerState,OntModel ontModel);


    // Property http://www.owl-ontologies.com/Datacenter.owl#runningTasks
    Collection getRunningTasks();

    RDFProperty getRunningTasksProperty();

    boolean hasRunningTasks();

    Iterator listRunningTasks();

    void addRunningTasks(Task newRunningTasks,OntModel model);
    //void addRunningTasks(Task newRunningTasks);

    void removeRunningTasks(Task oldRunningTasks, OntModel model);
    void removeRunningTasks(Task oldRunningTasks);

    void setRunningTasks(Collection newRunningTasks,OntModel model);
    void setRunningTasks(Collection newRunningTasks);
// Property http://www.owl-ontologies.com/Datacenter.owl#serverName

    String getServerName();

    RDFProperty getServerNameProperty();

    boolean hasServerName();

    void setServerName(String newServerName);

    // Property http://www.owl-ontologies.com/Datacenter.owl#webService
    String getWebService();

    RDFProperty getWebServiceProperty();

    boolean hasWebService();

    void setWebService(String newWebService);

    public boolean hasResourcesFor(Task task );

    @Override
    String toString();

    public boolean containsTask(Task task);

    boolean optimumValuesRespected();

}

