package greenContextOntology;

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Datacenter.owl#TaskInfo
 *
 * @version generated on Sat Mar 06 16:14:39 EET 2010
 */
public interface TaskInfo extends ContextElement {
}
