package greenContextOntology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
 
import greenContextOntology.Entity;
import greenContextOntology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://swrl.stanford.edu/ontologies/3.3/swrla.owl#Entity
 *
 * @version generated on Sat Mar 06 16:14:39 EET 2010
 */
public class DefaultEntity extends DefaultRDFIndividual
         implements Entity {

    public DefaultEntity(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultEntity() {
    }
}
