package ontologyRepresentations.selfHealingOntology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;
import ontologyRepresentations.selfHealingOntology.Action;
import ontologyRepresentations.selfHealingOntology.Sensor;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Ontology1230214892.owl#Action
 *
 * @version generated on Wed Mar 17 12:47:46 EET 2010
 */
public class DefaultAction extends DefaultContextElement
         implements Action {

    public DefaultAction(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultAction() {
    }



    // Property http://www.owl-ontologies.com/Ontology1230214892.owl#associatedResources

    public Sensor getAssociatedResources() {
        return (Sensor) getPropertyValueAs(getAssociatedResourcesProperty(), Sensor.class);
    }


    public RDFProperty getAssociatedResourcesProperty() {
        final String uri = "http://www.owl-ontologies.com/Ontology1230214892.owl#associatedResources";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasAssociatedResources() {
        return getPropertyValueCount(getAssociatedResourcesProperty()) > 0;
    }


    public void setAssociatedResources(Sensor newAssociatedResources) {
        setPropertyValue(getAssociatedResourcesProperty(), newAssociatedResources);
    }



    // Property http://www.owl-ontologies.com/Ontology1230214892.owl#effect

    public String getEffect() {
        return (String) getPropertyValue(getEffectProperty());
    }


    public RDFProperty getEffectProperty() {
        final String uri = "http://www.owl-ontologies.com/Ontology1230214892.owl#effect";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasEffect() {
        return getPropertyValueCount(getEffectProperty()) > 0;
    }


    public void setEffect(String newEffect) {
        setPropertyValue(getEffectProperty(), newEffect);
    }
}
