package ontologyRepresentations.selfHealingOntology.impl;

import com.hp.hpl.jena.ontology.Individual;
import com.hp.hpl.jena.ontology.OntModel;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.RDFNode;
import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;
import edu.stanford.smi.protegex.owl.model.impl.DefaultOWLIndividual;
import ontologyRepresentations.selfHealingOntology.Entity;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://swrl.stanford.edu/ontologies/3.3/swrla.owl#Entity
 *
 * @version generated on Wed Mar 17 12:47:46 EET 2010
 */
public class DefaultEntity extends DefaultOWLIndividual
        implements Entity {

    public DefaultEntity(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultEntity() {
    }
 
    public void setPropertyValue(RDFProperty rdfProperty, Object o, OntModel ontModel) {
        super.setPropertyValue(rdfProperty, o);    //To change body of overridden methods use File | Settings | File Templates.
        Individual targetIndividual = ontModel.getIndividual(this.getName());
        Property targetProperty = ontModel.getProperty(rdfProperty.getName());
        targetIndividual.setPropertyValue(targetProperty, ontModel.createLiteralStatement(
                targetIndividual, targetProperty, o).getLiteral().as(RDFNode.class));
    }
}
