package greenContextOntology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import greenContextOntology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Datacenter.owl#Received
 *
 * @version generated on Sun Mar 07 13:11:11 EET 2010
 */
public class DefaultReceived extends DefaultTaskInfo
         implements Received {

    public DefaultReceived(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultReceived() {
    }
}
