package greenContextOntology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import greenContextOntology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Datacenter.owl#Component
 *
 * @version generated on Sun Mar 07 13:11:11 EET 2010
 */
public class DefaultComponent extends DefaultResource
         implements Component {

    public DefaultComponent(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultComponent() {
    }



    // Property http://www.owl-ontologies.com/Datacenter.owl#optimum

    public int getOptimum() {
        return getPropertyValueLiteral(getOptimumProperty()).getInt();
    }


    public RDFProperty getOptimumProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#optimum";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasOptimum() {
        return getPropertyValueCount(getOptimumProperty()) > 0;
    }


    public void setOptimum(int newOptimum) {
        setPropertyValue(getOptimumProperty(), new java.lang.Integer(newOptimum));
    }



    // Property http://www.owl-ontologies.com/Datacenter.owl#total

    public int getTotal() {
        return getPropertyValueLiteral(getTotalProperty()).getInt();
    }


    public RDFProperty getTotalProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#total";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasTotal() {
        return getPropertyValueCount(getTotalProperty()) > 0;
    }


    public void setTotal(int newTotal) {
        setPropertyValue(getTotalProperty(), new java.lang.Integer(newTotal));
    }



    // Property http://www.owl-ontologies.com/Datacenter.owl#used

    public int getUsed() {
        return getPropertyValueLiteral(getUsedProperty()).getInt();
    }


    public RDFProperty getUsedProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#used";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasUsed() {
        return getPropertyValueCount(getUsedProperty()) > 0;
    }


    public void setUsed(int newUsed) {
        setPropertyValue(getUsedProperty(), new java.lang.Integer(newUsed));
    }
}
