package greenContextOntology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import java.util.*;

import greenContextOntology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Datacenter.owl#Policy
 *
 * @version generated on Sun Mar 07 13:11:11 EET 2010
 */
public class DefaultPolicy extends DefaultContextElement
         implements Policy {

    public DefaultPolicy(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultPolicy() {
    }



    // Property http://www.owl-ontologies.com/Datacenter.owl#references

    public Collection getReferences() {
        return getPropertyValues(getReferencesProperty());
    }


    public RDFProperty getReferencesProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#references";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasReferences() {
        return getPropertyValueCount(getReferencesProperty()) > 0;
    }


    public Iterator listReferences() {
        return listPropertyValues(getReferencesProperty());
    }


    public void addReferences(Object newReferences) {
        addPropertyValue(getReferencesProperty(), newReferences);
    }


    public void removeReferences(Object oldReferences) {
        removePropertyValue(getReferencesProperty(), oldReferences);
    }


    public void setReferences(Collection newReferences) {
        setPropertyValues(getReferencesProperty(), newReferences);
    }



    // Property http://www.owl-ontologies.com/Datacenter.owl#respected

    public boolean getRespected() {
        return getPropertyValueLiteral(getRespectedProperty()).getBoolean();

        return getPropertyValueLiteral(getRespectedProperty())!=null ;
    }


    public RDFProperty getRespectedProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#respected";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasRespected() {
        return getPropertyValueCount(getRespectedProperty()) > 0;
    }


    public void setRespected(boolean newRespected) {
        setPropertyValue(getRespectedProperty(), new java.lang.Boolean(newRespected));
    }
}
