package greenContextOntology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import java.util.*;

import greenContextOntology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Datacenter.owl#EnergyPolicy
 *
 * @version generated on Sun Mar 07 13:11:11 EET 2010
 */
public class DefaultEnergyPolicy extends DefaultPolicy
         implements EnergyPolicy {

    public DefaultEnergyPolicy(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultEnergyPolicy() {
    }

  

    // Property http://www.owl-ontologies.com/Datacenter.owl#referenced

    public Server getReferenced() {
        return (Server) getPropertyValueAs(getReferencedProperty(), Server.class);
    }


    public RDFProperty getReferencedProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#referenced";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasReferenced() {
        return getPropertyValueCount(getReferencedProperty()) > 0;
    }


    public void setReferenced(Server newReferenced) {
        setPropertyValue(getReferencedProperty(), newReferenced);
    }
 
}
