package greenContextOntology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import greenContextOntology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://swrl.stanford.edu/ontologies/3.3/swrla.owl#Entity
 *
 * @version generated on Sun Mar 07 13:11:11 EET 2010
 */
 public class DefaultEntity extends DefaultOWLIndividual
         implements Entity {

    public DefaultEntity(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultEntity() {
    }
}
