package greenContextOntology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import greenContextOntology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Datacenter.owl#Memory
 *
 * @version generated on Sun Mar 07 13:11:11 EET 2010
 */
public class DefaultMemory extends DefaultComponent
         implements Memory {

    public DefaultMemory(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultMemory() {
    }



    // Property http://www.owl-ontologies.com/Datacenter.owl#weight

    public float getWeight() {
        return getPropertyValueLiteral(getWeightProperty()).getFloat();
    }


    public RDFProperty getWeightProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#weight";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasWeight() {
        return getPropertyValueCount(getWeightProperty()) > 0;
    }


    public void setWeight(float newWeight) {
        setPropertyValue(getWeightProperty(), new java.lang.Float(newWeight));
    }
}
