package greenContextOntology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

import greenContextOntology.*;
import greenContextOntology.Task;
import com.hp.hpl.jena.ontology.OntModel;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Datacenter.owl#QoSPolicy
 *
 * @version generated on Sun Mar 07 13:11:11 EET 2010
 */
public class DefaultQoSPolicy extends DefaultPolicy
        implements QoSPolicy {

    public DefaultQoSPolicy(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultQoSPolicy() {
    }


    public boolean getRespected(OntModel ontModel) {
        Task task = this.getReferenced();
        TaskInfo receivedInfo = task.getReceivedInfo();
        TaskInfo requestedInfo = task.getRequestedInfo();
        
        if (receivedInfo.getCores() < requestedInfo.getCores()) {
            return false;
        }
        if (receivedInfo.getCpu() < requestedInfo.getCpu()) {
            return false;
        }
        if (receivedInfo.getMemory() < requestedInfo.getMemory()) {
            return false;
        }
        if (receivedInfo.getStorage() < requestedInfo.getStorage()) {
            return false;
        }
        
        return true;
    }

// Property http://www.owl-ontologies.com/Datacenter.owl#referenced

    public Task getReferenced() {
        return (Task) getPropertyValueAs(getReferencedProperty(), Task.class);
    }


    public RDFProperty getReferencedProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#referenced";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasReferenced() {
        return getPropertyValueCount(getReferencedProperty()) > 0;
    }


    public void setReferenced(Task newReferenced) {
        setPropertyValue(getReferencedProperty(), newReferenced);
    }
}
