package greenContextOntology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import greenContextOntology.*;

import java.util.Collection;
import java.util.Iterator;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Datacenter.owl#TaskInfo
 *
 * @version generated on Sun Mar 07 13:11:11 EET 2010
 */
public class DefaultTaskInfo extends DefaultContextElement
        implements TaskInfo {

    public DefaultTaskInfo(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultTaskInfo() {
    }


    // Property http://www.owl-ontologies.com/Datacenter.owl#cores

    public int getCores() {
        return getPropertyValueLiteral(getCoresProperty()).getInt();
    }


    public RDFProperty getCoresProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#cores";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasCores() {
        return getPropertyValueCount(getCoresProperty()) > 0;
    }


    public void setCores(int newCores) {
        setPropertyValue(getCoresProperty(), new java.lang.Integer(newCores));
    }


    // Property http://www.owl-ontologies.com/Datacenter.owl#cpu

    public int getCpu() {
        return getPropertyValueLiteral(getCpuProperty()).getInt();
    }


    public RDFProperty getCpuProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#cpu";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasCpu() {
        return getPropertyValueCount(getCpuProperty()) > 0;
    }


    public void setCpu(int newCpu) {
        setPropertyValue(getCpuProperty(), new java.lang.Integer(newCpu));
    }

    // Property http://www.owl-ontologies.com/Datacenter.owl#memory

    public int getMemory() {
        return getPropertyValueLiteral(getMemoryProperty()).getInt();
    }


    public RDFProperty getMemoryProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#memory";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasMemory() {
        return getPropertyValueCount(getMemoryProperty()) > 0;
    }


    public void setMemory(int newMemory) {
        setPropertyValue(getMemoryProperty(), new java.lang.Integer(newMemory));
    }


    // Property http://www.owl-ontologies.com/Datacenter.owl#storage

    public int getStorage() {
        return getPropertyValueLiteral(getStorageProperty()).getInt();
    }


    public RDFProperty getStorageProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#storage";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasStorage() {
        return getPropertyValueCount(getStorageProperty()) > 0;
    }


    public void setStorage(int newStorage) {
        setPropertyValue(getStorageProperty(), new java.lang.Integer(newStorage));
    }


    // Property http://www.owl-ontologies.com/Datacenter.owl#taskProperty

    public Collection getTaskProperty() {
        return getPropertyValues(getTaskPropertyProperty());
    }


    public RDFProperty getTaskPropertyProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#taskProperty";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasTaskProperty() {
        return getPropertyValueCount(getTaskPropertyProperty()) > 0;
    }


    public Iterator listTaskProperty() {
        return listPropertyValues(getTaskPropertyProperty());
    }


    public void addTaskProperty(Object newTaskProperty) {
        addPropertyValue(getTaskPropertyProperty(), newTaskProperty);
    }


    public void removeTaskProperty(Object oldTaskProperty) {
        removePropertyValue(getTaskPropertyProperty(), oldTaskProperty);
    }


    public void setTaskProperty(Collection newTaskProperty) {
        setPropertyValues(getTaskPropertyProperty(), newTaskProperty);
    }

    // Property http://www.owl-ontologies.com/Datacenter.owl#receivedCoreIndex

    public Collection getReceivedCoreIndex() {
        return getPropertyValues(getReceivedCoreIndexProperty());
    }


    public RDFProperty getReceivedCoreIndexProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#receivedCoreIndex";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasReceivedCoreIndex() {
        return getPropertyValueCount(getReceivedCoreIndexProperty()) > 0;
    }


    public Iterator listReceivedCoreIndex() {
        return listPropertyValues(getReceivedCoreIndexProperty());
    }


    public void addReceivedCoreIndex(int newReceivedCoreIndex) {
        addPropertyValue(getReceivedCoreIndexProperty(), newReceivedCoreIndex);
    }


    public void removeReceivedCoreIndex(int oldReceivedCoreIndex) {
        removePropertyValue(getReceivedCoreIndexProperty(), oldReceivedCoreIndex);
    }


    public void setReceivedCoreIndex(Collection newReceivedCoreIndex) {
        setPropertyValues(getReceivedCoreIndexProperty(), newReceivedCoreIndex);
    }

}
