package greenContextOntology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import greenContextOntology.Memory;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Datacenter.owl#Memory
 *
 * @version generated on Sun Mar 07 13:11:11 EET 2010
 */
public class DefaultMemory extends DefaultComponent
         implements Memory {

    public DefaultMemory(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultMemory() {
    }



   
}
