package greenContextOntology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
 
import greenContextOntology.Requested;
import greenContextOntology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Datacenter.owl#Requested
 *
 * @version generated on Sat Mar 06 16:14:39 EET 2010
 */
public class DefaultRequested extends DefaultTaskInfo
         implements Requested {

    public DefaultRequested(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultRequested() {
    }
}
