package greenContextOntology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import greenContextOntology.Action;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Datacenter.owl#Action
 *
 * @version generated on Sun Mar 07 13:11:11 EET 2010
 */
public class DefaultAction extends DefaultActor
         implements Action {

    public DefaultAction(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultAction() {
    }
}
