package greenContextOntology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
 
import greenContextOntology.Core;
import greenContextOntology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Datacenter.owl#Core
 *
 * @version generated on Sat Mar 06 16:14:39 EET 2010
 */
public class DefaultCore extends DefaultComponent
         implements Core {

    public DefaultCore(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultCore() {
    }
}
