package greenContextOntology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import greenContextOntology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Datacenter.owl#ContextElement
 *
 * @version generated on Sun Mar 07 13:11:11 EET 2010
 */
public class DefaultContextElement extends DefaultRDFIndividual
         implements ContextElement {

    public DefaultContextElement(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultContextElement() {
    }
}
