package selfHealingOntology;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

import java.util.Collection;
import java.util.Iterator;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Ontology1230214892.owl#Actuator
 *
 * @version generated on Wed Mar 17 12:47:46 EET 2010
 */
public interface Actuator extends PhysicalResource {

    // Property http://www.owl-ontologies.com/Ontology1230214892.owl#associatedActions

    Collection getAssociatedActions();

    RDFProperty getAssociatedActionsProperty();

    boolean hasAssociatedActions();

    Iterator listAssociatedActions();

    void addAssociatedActions(Action newAssociatedActions);

    void removeAssociatedActions(Action oldAssociatedActions);

    void setAssociatedActions(Collection newAssociatedActions);
}
