package selfHealingOntology;

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Ontology1230214892.owl#ContextElement
 *
 * @version generated on Wed Mar 17 12:47:46 EET 2010
 */
public interface ContextElement extends OWLIndividual {
    
}
