package selfHealingOntology;

import edu.stanford.smi.protegex.owl.model.OWLIndividual;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://swrl.stanford.edu/ontologies/3.3/swrla.owl#Entity
 *
 * @version generated on Wed Mar 17 12:47:46 EET 2010
 */
public interface Entity extends OWLIndividual {
}
