package selfHealingOntology;

import com.hp.hpl.jena.ontology.OntModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;

import java.util.Collection;
import java.util.Iterator;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Ontology1230214892.owl#Policy
 *
 * @version generated on Wed Mar 17 12:47:46 EET 2010
 */
public interface Policy extends ContextElement {

    // Property http://www.owl-ontologies.com/Ontology1230214892.owl#EvaluatePolicyP

    boolean getEvaluatePolicyP(OntModel ontModel);

    RDFProperty getEvaluatePolicyPProperty();

    boolean hasEvaluatePolicyP();

    void setEvaluatePolicyP(boolean newEvaluatePolicyP);


    // Property http://www.owl-ontologies.com/Ontology1230214892.owl#associatedResources

    Collection getAssociatedResources();

    RDFProperty getAssociatedResourcesProperty();

    boolean hasAssociatedResources();

    Iterator listAssociatedResources();

    void addAssociatedResources(Sensor newAssociatedResources);

    void removeAssociatedResources(Sensor oldAssociatedResources);

    void setAssociatedResources(Collection newAssociatedResources);
}
