package greenContextOntology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
 
import java.util.*;

import greenContextOntology.EnergyPolicy;
import greenContextOntology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Datacenter.owl#EnergyPolicy
 *
 * @version generated on Sat Mar 06 16:14:39 EET 2010
 */
public class DefaultEnergyPolicy extends DefaultPolicy
         implements EnergyPolicy {

    public DefaultEnergyPolicy(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultEnergyPolicy() {
    }



    // Property http://www.owl-ontologies.com/Datacenter.owl#references

    public Collection getReferences() {
        return getPropertyValuesAs(getReferencesProperty(), Server.class);
    }


    public RDFProperty getReferencesProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#references";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasReferences() {
        return getPropertyValueCount(getReferencesProperty()) > 0;
    }


    public Iterator listReferences() {
        return listPropertyValuesAs(getReferencesProperty(), Server.class);
    }


    public void addReferences(Server newReferences) {
        addPropertyValue(getReferencesProperty(), newReferences);
    }


    public void removeReferences(Server oldReferences) {
        removePropertyValue(getReferencesProperty(), oldReferences);
    }


    public void setReferences(Collection newReferences) {
        setPropertyValues(getReferencesProperty(), newReferences);
    }
}
