package greenContextOntology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
 
import java.util.*;

import greenContextOntology.Task;
import greenContextOntology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Datacenter.owl#Task
 *
 * @version generated on Sat Mar 06 16:14:39 EET 2010
 */
public class DefaultTask extends DefaultContextElement
         implements Task {

    public DefaultTask(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultTask() {
    }



    // Property http://www.owl-ontologies.com/Datacenter.owl#associatedInfo

    public Collection getAssociatedInfo() {
        return getPropertyValuesAs(getAssociatedInfoProperty(), TaskInfo.class);
    }


    public RDFProperty getAssociatedInfoProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#associatedInfo";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasAssociatedInfo() {
        return getPropertyValueCount(getAssociatedInfoProperty()) > 0;
    }


    public Iterator listAssociatedInfo() {
        return listPropertyValuesAs(getAssociatedInfoProperty(), TaskInfo.class);
    }


    public void addAssociatedInfo(TaskInfo newAssociatedInfo) {
        addPropertyValue(getAssociatedInfoProperty(), newAssociatedInfo);
    }


    public void removeAssociatedInfo(TaskInfo oldAssociatedInfo) {
        removePropertyValue(getAssociatedInfoProperty(), oldAssociatedInfo);
    }


    public void setAssociatedInfo(Collection newAssociatedInfo) {
        setPropertyValues(getAssociatedInfoProperty(), newAssociatedInfo);
    }



    // Property http://www.owl-ontologies.com/Datacenter.owl#cores

    public Collection getCores() {
        return getPropertyValues(getCoresProperty());
    }


    public RDFProperty getCoresProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#cores";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasCores() {
        return getPropertyValueCount(getCoresProperty()) > 0;
    }


    public Iterator listCores() {
        return listPropertyValues(getCoresProperty());
    }


    public void addCores(int newCores) {
        addPropertyValue(getCoresProperty(), newCores);
    }


    public void removeCores(int oldCores) {
        removePropertyValue(getCoresProperty(), oldCores);
    }


    public void setCores(Collection newCores) {
        setPropertyValues(getCoresProperty(), newCores);
    }



    // Property http://www.owl-ontologies.com/Datacenter.owl#cpu

    public Collection getCpu() {
        return getPropertyValues(getCpuProperty());
    }


    public RDFProperty getCpuProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#cpu";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasCpu() {
        return getPropertyValueCount(getCpuProperty()) > 0;
    }


    public Iterator listCpu() {
        return listPropertyValues(getCpuProperty());
    }


    public void addCpu(int newCpu) {
        addPropertyValue(getCpuProperty(), newCpu);
    }


    public void removeCpu(int oldCpu) {
        removePropertyValue(getCpuProperty(), oldCpu);
    }


    public void setCpu(Collection newCpu) {
        setPropertyValues(getCpuProperty(), newCpu);
    }



    // Property http://www.owl-ontologies.com/Datacenter.owl#memory

    public Collection getMemory() {
        return getPropertyValues(getMemoryProperty());
    }


    public RDFProperty getMemoryProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#memory";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasMemory() {
        return getPropertyValueCount(getMemoryProperty()) > 0;
    }


    public Iterator listMemory() {
        return listPropertyValues(getMemoryProperty());
    }


    public void addMemory(int newMemory) {
        addPropertyValue(getMemoryProperty(), newMemory);
    }


    public void removeMemory(int oldMemory) {
        removePropertyValue(getMemoryProperty(), oldMemory);
    }


    public void setMemory(Collection newMemory) {
        setPropertyValues(getMemoryProperty(), newMemory);
    }



    // Property http://www.owl-ontologies.com/Datacenter.owl#name

    public String getName() {
        return (String) getPropertyValue(getNameProperty());
    }


    public RDFProperty getNameProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#name";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasName() {
        return getPropertyValueCount(getNameProperty()) > 0;
    }


    public void setName(String newName) {
        setPropertyValue(getNameProperty(), newName);
    }



    // Property http://www.owl-ontologies.com/Datacenter.owl#storage

    public Collection getStorage() {
        return getPropertyValues(getStorageProperty());
    }


    public RDFProperty getStorageProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#storage";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasStorage() {
        return getPropertyValueCount(getStorageProperty()) > 0;
    }


    public Iterator listStorage() {
        return listPropertyValues(getStorageProperty());
    }


    public void addStorage(int newStorage) {
        addPropertyValue(getStorageProperty(), newStorage);
    }


    public void removeStorage(int oldStorage) {
        removePropertyValue(getStorageProperty(), oldStorage);
    }


    public void setStorage(Collection newStorage) {
        setPropertyValues(getStorageProperty(), newStorage);
    }



    // Property http://www.owl-ontologies.com/Datacenter.owl#taskProperty

    public Collection getTaskProperty() {
        return getPropertyValues(getTaskPropertyProperty());
    }


    public RDFProperty getTaskPropertyProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#taskProperty";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasTaskProperty() {
        return getPropertyValueCount(getTaskPropertyProperty()) > 0;
    }


    public Iterator listTaskProperty() {
        return listPropertyValues(getTaskPropertyProperty());
    }


    public void addTaskProperty(Object newTaskProperty) {
        addPropertyValue(getTaskPropertyProperty(), newTaskProperty);
    }


    public void removeTaskProperty(Object oldTaskProperty) {
        removePropertyValue(getTaskPropertyProperty(), oldTaskProperty);
    }


    public void setTaskProperty(Collection newTaskProperty) {
        setPropertyValues(getTaskPropertyProperty(), newTaskProperty);
    }
}
