package ontologyRepresentations.greenContextOntology.impl;

import com.hp.hpl.jena.ontology.OntModel;
import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;
import ontologyRepresentations.greenContextOntology.DatacenterProtegeFactory;
import ontologyRepresentations.greenContextOntology.ReceivedTaskInfo;

import java.util.Collection;
import java.util.Iterator;
import java.util.UUID;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Datacenter.owl#ReceivedTaskInfo
 *
 * @version generated on Thu Apr 15 14:24:33 EEST 2010
 */
public class DefaultReceivedTaskInfo extends DefaultContextElement
        implements ReceivedTaskInfo {

    public DefaultReceivedTaskInfo(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    public DefaultReceivedTaskInfo() {
    }

    // Property http://www.owl-ontologies.com/Datacenter.owl#cores
    public int getCores() {
        if (hasCores()) {
            return getPropertyValueLiteral(getCoresProperty()).getInt();
        } else {
            return 0;
        }
    }

    public RDFProperty getCoresProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#cores";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasCores() {
        return getPropertyValueCount(getCoresProperty()) > 0;
    }

    public void setCores(int newCores) {
        setPropertyValue(getCoresProperty(), new java.lang.Integer(newCores));
    }

    public void setCores(int newCores, OntModel model) {
        setPropertyValue(getCoresProperty(), new java.lang.Integer(newCores), model);
    }

    // Property http://www.owl-ontologies.com/Datacenter.owl#cpuReceived
    public int getCpuReceived() {
        if (hasCpuReceived()) {
            return getPropertyValueLiteral(getCpuReceivedProperty()).getInt();
        } else {
            return 0;
        }
    }

    public RDFProperty getCpuReceivedProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#cpuReceived";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasCpuReceived() {
        return getPropertyValueCount(getCpuReceivedProperty()) > 0;
    }

    public void setCpuReceived(int newCpuReceived) {
        setPropertyValue(getCpuReceivedProperty(), new java.lang.Integer(newCpuReceived));
    }

    public void setCpuReceived(int newCpuReceived, OntModel model) {
        setPropertyValue(getCpuReceivedProperty(), new java.lang.Integer(newCpuReceived), model);
    }

    // Property http://www.owl-ontologies.com/Datacenter.owl#memoryReceived
    public int getMemoryReceived() {
        if (hasMemoryReceived()) {
            return getPropertyValueLiteral(getMemoryReceivedProperty()).getInt();
        } else {
            return 0;
        }
    }

    public RDFProperty getMemoryReceivedProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#memoryReceived";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasMemoryReceived() {
        return getPropertyValueCount(getMemoryReceivedProperty()) > 0;
    }

    public void setMemoryReceived(int newMemoryReceived) {
        setPropertyValue(getMemoryReceivedProperty(), new java.lang.Integer(newMemoryReceived));
    }

    public void setMemoryReceived(int newMemoryReceived, OntModel model) {
        setPropertyValue(getMemoryReceivedProperty(), new java.lang.Integer(newMemoryReceived), model);
    }

    // Property http://www.owl-ontologies.com/Datacenter.owl#storageReceived
    public int getStorageReceived() {
        if (hasMemoryReceived()) {
            return getPropertyValueLiteral(getStorageReceivedProperty()).getInt();
        } else {
            return 0;
        }
    }

    public RDFProperty getStorageReceivedProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#storageReceived";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasStorageReceived() {
        return getPropertyValueCount(getStorageReceivedProperty()) > 0;
    }

    public void setStorageReceived(int newStorageReceived) {
        setPropertyValue(getStorageReceivedProperty(), new java.lang.Integer(newStorageReceived));
    }

    public void setStorageReceived(int newStorageReceived, OntModel model) {
        setPropertyValue(getStorageReceivedProperty(), new java.lang.Integer(newStorageReceived), model);
    }

    // Property http://www.owl-ontologies.com/Datacenter.owl#receivedCoreIndex
    public Collection getReceivedCoreIndex() {
        return getPropertyValues(getReceivedCoreIndexProperty());
    }

    public RDFProperty getReceivedCoreIndexProperty() {
        final String uri = "http://www.owl-ontologies.com/Datacenter.owl#receivedCoreIndex";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasReceivedCoreIndex() {
        return getPropertyValueCount(getReceivedCoreIndexProperty()) > 0;
    }

    public Iterator listReceivedCoreIndex() {
        return listPropertyValues(getReceivedCoreIndexProperty());
    }

    public void addReceivedCoreIndex(int newReceivedCoreIndex) {
        addPropertyValue(getReceivedCoreIndexProperty(), newReceivedCoreIndex);
    }

    public void removeReceivedCoreIndex(int oldReceivedCoreIndex) {
        removePropertyValue(getReceivedCoreIndexProperty(), oldReceivedCoreIndex);
    }

    public void setReceivedCoreIndex(Collection newReceivedCoreIndex) {
        setPropertyValues(getReceivedCoreIndexProperty(), newReceivedCoreIndex);
    }

    public Object clone(DatacenterProtegeFactory protegeFactory) {
        ReceivedTaskInfo taskInfo = protegeFactory.createReceivedTaskInfo(this.getLocalName() + "_" + UUID.randomUUID());
        taskInfo.setCores(0);
        taskInfo.setCpuReceived(0);
        taskInfo.setMemoryReceived(0);
        taskInfo.setStorageReceived(0);
        return taskInfo;
    }
}

     
