package contextawaremodel.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import contextawaremodel.ontology.physical_resource;
import contextawaremodel.ontology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Ontology1240758175.owl#physical-resource
 *
 * @version generated on Sun Apr 26 18:19:44 EEST 2009
 */
public class Defaultphysical_resource extends Defaultresource
         implements physical_resource {

    public Defaultphysical_resource(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public Defaultphysical_resource() {
    }
}
