package contextawaremodel.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import contextawaremodel.ontology.actor;
import contextawaremodel.ontology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Ontology1240758175.owl#actor
 *
 * @version generated on Sun Apr 26 18:19:44 EEST 2009
 */
public class Defaultactor extends Defaultcontext_element
         implements actor {

    public Defaultactor(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public Defaultactor() {
    }
}
