package contextawaremodel.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import contextawaremodel.ontology.context_element;
import contextawaremodel.ontology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Ontology1240758175.owl#context-element
 *
 * @version generated on Sun Apr 26 18:19:44 EEST 2009
 */
public class Defaultcontext_element extends DefaultRDFIndividual
         implements context_element {

    public Defaultcontext_element(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public Defaultcontext_element() {
    }
}
