package contextawaremodel.ontology;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Ontology1240758175.owl#actor-resource
 *
 * @version generated on Sun Apr 26 18:19:44 EEST 2009
 */
public interface actor_resource extends resource {
}
