package contextawaremodel.ontology;

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Ontology1240758175.owl#policy
 *
 * @version generated on Sun Apr 26 18:19:44 EEST 2009
 */
public interface policy extends context_element {
}
