package selfHealingOntology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import selfHealingOntology.Resource;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Ontology1230214892.owl#Resource
 *
 * @version generated on Wed Mar 17 12:47:46 EET 2010
 */
public class DefaultResource extends DefaultContextElement
         implements Resource {

    public DefaultResource(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultResource() {
    }
    
}
