package selfHealingOntology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import selfHealingOntology.PhysicalResource;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Ontology1230214892.owl#PhysicalResource
 *
 * @version generated on Wed Mar 17 12:47:46 EET 2010
 */
public class DefaultPhysicalResource extends DefaultResource
         implements PhysicalResource {

    public DefaultPhysicalResource(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultPhysicalResource() {
    }
}
